export const IS_LOADING = "IS_LOADING";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const RESET_PLAYLISTS = "RESET_PLAYLISTS";
export const CURRENTLY_PLAYING = "CURRENTLY_PLAYING";
export const SET_OPENED_PLAYLIST = "SET_OPENED_PKAYLIST";
export const RESET_OPENED_PLAYLIST = "RESET_OPENED_PKAYLIST";
