export const LOADING_TRACKS = "LOADING_TRACKS";
export const SET_RECENT_TRACKS = "SET_RECENT_TRACKS";
export const RESET_TRACKS = "RESET_TRACKS";
export const CURRENT_PLAYING_TRACK = "CURRENT_PLAYING_TRACK";
export const SET_PLAYING = "SET_PLAYING";
